language: node_js # language
node_js:
  - "v11.14.0"  # nodejs version
branches:
  only:
  - main    # build branch
cache:
  directories:
  - node_modules # cache dir
before_install:
  - export TZ='Asia/Shanghai'  # set timezone
install:
  - npm install -g gitbook-cli # install compile tool
  - gitbook install
script:
  - gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./_book/  # static output
  target-branch: gh-pages
  verbose: true
  on:
    branch: main
